[versions]
androidGradlePlugin = "8.1.2"
androidxActivity = "1.8.0"
androidxComposeCompiler = "1.5.3"
androidxCore = "1.12.0"
androidxJunit = "1.1.5"
androidxLifecycle = "2.6.2"
androidxNavigation = "2.7.5"
espressoCore = "3.5.1"
gson = "2.10.1"
hilt = "2.48"
hiltNavigationCompose = "1.1.0"
junit4 = "4.13.2"
kotlin = "1.9.10"
kotlinxCoroutinesAndroid = "1.7.3"
timber = "5.0.1"
introShowcaseView = "1.0.5"
ksp = "1.9.0-1.0.12"
androidxComposeBom = "2023.10.01"
appcompat = "1.6.1"
material = "1.10.0"

[libraries]
android-tools-build-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-compiler = { group = "androidx.compose.compiler", name = "compiler", version.ref = "androidxComposeCompiler" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-junit = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
introShowcaseView = { group = "com.canopas.intro-showcase-view", name = "introshowcaseview", version.ref = "introShowcaseView" }


[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
com-android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
partymania-android-application = { id = "partymania.android.application", version = "unspecified" }
partymania-android-library = { id = "partymania.android.library", version = "unspecified" }
partymania-compose = { id = "partymania.compose", version = "unspecified" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
