name: Android CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  prepare:
    name: Prepare Keystore
    runs-on: ubuntu-latest
    steps:
      - name: Create dummy keystore.properties
        run: |
          echo "keyAlias=debug" > keystore.properties
          echo "keyPassword=android" >> keystore.properties
          echo "storeFile=debug.keystore" >> keystore.properties
          echo "storePassword=android" >> keystore.properties

      - name: Upload keystore.properties
        uses: actions/upload-artifact@v4
        with:
          name: keystore-properties
          path: keystore.properties
          retention-days: 1

  lint:
    name: Run Detekt
    runs-on: ubuntu-latest
    needs: [ prepare ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Download keystore.properties
        uses: actions/download-artifact@v4
        with:
          name: keystore-properties

      - name: Run Detekt
        run: ./gradlew detekt

  build:
    name: Build Debug APK
    runs-on: ubuntu-latest
    needs: [ lint, prepare ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Download keystore.properties
        uses: actions/download-artifact@v4
        with:
          name: keystore-properties

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [ lint, prepare ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Download keystore.properties
        uses: actions/download-artifact@v4
        with:
          name: keystore-properties

      - name: Run unit tests
        run: ./gradlew test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/build/reports/tests/'
