name: Android Release

on:
  release:
    types: [ released ]

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Create keystore.properties
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
        run: |
          echo "keyAlias=$KEY_ALIAS" > keystore.properties
          echo "keyPassword=$KEY_PASSWORD" >> keystore.properties
          echo "storeFile=release.keystore" >> keystore.properties
          echo "storePassword=$STORE_PASSWORD" >> keystore.properties
          echo $KEYSTORE_BASE64 | base64 -d > release.keystore

      - name: Build release APK
        run: ./gradlew assembleRelease

      - name: Get version name from release
        id: get_version
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          echo "VERSION=${TAG_NAME#v}" >> $GITHUB_OUTPUT

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: app/build/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
