name: Android CI

on:
  pull_request:
    branches: [ main, develop ]

permissions:
  pull-requests: write

jobs:
  prepare:
    name: Prepare Keystore
    runs-on: ubuntu-latest
    steps:
      - name: Create dummy keystore.properties
        run: |
          echo "keyAlias=debug" > keystore.properties
          echo "keyPassword=android" >> keystore.properties
          echo "storeFile=debug.keystore" >> keystore.properties
          echo "storePassword=android" >> keystore.properties

      - name: Upload keystore.properties
        uses: actions/upload-artifact@v4
        with:
          name: keystore-properties
          path: keystore.properties
          retention-days: 1

  lint:
    name: Run Detekt
    runs-on: ubuntu-latest
    needs: [ prepare ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Download keystore.properties
        uses: actions/download-artifact@v4
        with:
          name: keystore-properties

      - name: Run Detekt
        run: ./gradlew detekt

  build:
    name: Build Debug APK
    runs-on: ubuntu-latest
    needs: [ lint, prepare ]
    outputs:
      artifact-id: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Download keystore.properties
        uses: actions/download-artifact@v4
        with:
          name: keystore-properties

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        id: artifact-upload-step
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/free/debug/app-free-debug.apk

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: [ lint, prepare ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Download keystore.properties
        uses: actions/download-artifact@v4
        with:
          name: keystore-properties

      - name: Run unit tests
        run: ./gradlew test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: '**/build/reports/tests/'
          retention-days: 14

  comment:
    name: Comment on PR
    runs-on: ubuntu-latest
    needs: [ build ]
    if: github.event_name == 'pull_request'
    steps:
      - name: Comment on PR with artifact link
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const artifactName = 'app-debug';
            const runId = context.runId;
            const artifactUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${runId}/artifacts/${{ needs.build.outputs.artifact-id }}`;

            const message = `### 📱 Debug APK Available\n\nYou can download the debug APK from here [App-debug.apk](${artifactUrl}).`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
