name: Merge Main into Develop

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]
  push:
    branches: [ improve-ci-cd ]

jobs:
  merge:
    name: Merge Main into Develop
    # Only run this job if the PR was merged or a direct push to main was made
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Set up Git
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Merge main into develop
        run: |
          echo "Fetching latest changes from remote..."
          git fetch origin main develop

          echo "Checking out develop branch..."
          git checkout develop

          echo "Merging main into develop..."
          if git merge origin/main; then
            echo "Merge successful, pushing changes..."
            git push origin develop
            echo "Successfully merged and pushed develop branch"
          else
            echo "Merge failed with conflicts. Aborting merge."
            git merge --abort
            exit 1
          fi
